Vagrant.configure(2) do |config|

    config.vm.define "trusty" do |config|
        config.vm.box = "ubuntu/trusty64"
        config.vm.hostname = "trusty"
        config.vm.provider "virtualbox" do |v|
            v.name = "trusty"
            v.memory = 2048
        end
        config.vm.network "forwarded_port", guest: 15672, host: 15672
        config.vm.network "forwarded_port", guest: 3000,  host: 3000
    end
end
